alias l='ls -alh'
alias c='clear'
alias ecr='aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 014157409456.dkr.ecr.us-west-2.amazonaws.com'
alias console='saml2aws login -a default; saml2aws console -a default'
alias nvchad='NVIM_APPNAME=nvchad nvim'
alias lazyvim='NVIM_APPNAME=lazyvim nvim'
